# 🐼 Pandas - Class 3: Data Cleaning Essentials
Welcome to **Class 3** of our Pandas series. Today we’ll learn how to clean and prepare data for analysis.

## Handling Missing Values
Real-world datasets often have missing data. Pandas offers:
- `isna()` / `isnull()` → detect missing values (returns True/False)
- `dropna()` → remove missing values (rows/columns)
- `fillna()` → replace missing values with a given value or method (e.g., forward fill)

Always inspect how much data is missing before deciding to drop or fill.

In [146]:
from numpy import printoptions
import pandas as pd
import numpy as np
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, None, 35, 40, None],
    "City": ["Delhi", "Mumbai", None, "Bangalore", "Chennai"],
    "Score": [85, 91, np.nan, 88, 95]
}

b = pd.DataFrame(a)
b
print(b.isna())
print("==============================="
)
print(b.dropna())
b['Age']=b['Age'].fillna(b['Age']).mean()
print(b)
print("===============================")
b['City']=b['City'].fillna(b['City']).mode()
print(b)
print("===============================")
b['Score']=b['Score'].fillna(b['Score']).mean()
print(b)

    Name    Age   City  Score
0  False  False  False  False
1  False   True  False  False
2  False  False   True   True
3  False  False  False  False
4  False   True  False  False
===============================
    Name   Age       City  Score
0  Alice  25.0      Delhi   85.0
3  David  40.0  Bangalore   88.0
      Name        Age       City  Score
0    Alice  33.333333      Delhi   85.0
1      Bob  33.333333     Mumbai   91.0
2  Charlie  33.333333        NaN    NaN
3    David  33.333333  Bangalore   88.0
4     Emma  33.333333    Chennai   95.0
===============================
      Name        Age       City  Score
0    Alice  33.333333  Bangalore   85.0
1      Bob  33.333333    Chennai   91.0
2  Charlie  33.333333      Delhi    NaN
3    David  33.333333     Mumbai   88.0
4     Emma  33.333333        NaN   95.0
===============================
      Name        Age       City  Score
0    Alice  33.333333  Bangalore  89.75
1      Bob  33.333333    Chennai  89.75
2  Charlie  33.333333      Delhi  89.75
3    David  33.333333     Mumbai  89.75
4     Emma  33.333333        NaN  89.75

## Changing Data Types (`astype`)
- Convert a column to a different type using `astype()`.
- Examples: converting strings to numbers, integers to floats, or columns to category.

Be careful: make sure the data is compatible with the new type!

In [147]:
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)
b['Score']=b['Score'].astype(float)
b

      Name  Age  Score
0    Alice   25   88.0
1      Bob   30   92.0
2  Charlie   35   79.0
3    David   40   85.0
4     Emma   22   95.0

## Replacing Values (`replace`)
- Use `replace()` to substitute specific values or patterns.
- Useful for cleaning labels, fixing typos, or mapping categories.

In [148]:
'''data = {
    "City": ["Bhopal", "Indore", "Bhopal", "Ujjain"]
}

df = pd.DataFrame(data)
# Replace "Bhopal" with "Sehore"
df["City"] = df["City"].replace("Bhopal", "Sehore")

print(df)'''

c=b.copy()
c
c['Name']=c['Name'].replace("David","Dhruv")
print(c)
print("==============================")
c['Score']=c['Score'].replace({88.0:99.2,95.0:65.4},)
print(c)

      Name  Age  Score
0    Alice   25   88.0
1      Bob   30   92.0
2  Charlie   35   79.0
3    Dhruv   40   85.0
4     Emma   22   95.0
==============================
      Name  Age  Score
0    Alice   25   99.2
1      Bob   30   92.0
2  Charlie   35   79.0
3    Dhruv   40   85.0
4     Emma   22   65.4

## Dropping Rows & Columns (`drop`)
- `drop(labels, axis=0)` → drop rows by index labels.
- `drop(labels, axis=1)` → drop columns by name.
- Use `inplace=True` if you want to modify the DataFrame directly.

In [149]:
# # Drop a row
# import pandas as pd

# df = pd.DataFrame({
#     "Name": ["Aman", "Riya", "Vikas"],
#     "Age": [20, 21, 22]
# })

# # Row with index 1 remove
# df = df.drop(1)

# print(df)
print(c)
c.drop(["Name"],axis=1)
print("=========================")
print(c)
print("=========================")

c.drop([1,4],axis=0)
print(c)

      Name  Age  Score
0    Alice   25   99.2
1      Bob   30   92.0
2  Charlie   35   79.0
3    Dhruv   40   85.0
4     Emma   22   65.4
=========================
      Name  Age  Score
0    Alice   25   99.2
1      Bob   30   92.0
2  Charlie   35   79.0
3    Dhruv   40   85.0
4     Emma   22   65.4
=========================
      Name  Age  Score
0    Alice   25   99.2
1      Bob   30   92.0
2  Charlie   35   79.0
3    Dhruv   40   85.0
4     Emma   22   65.4

In [150]:
# # Drop a column
# df = pd.DataFrame({
#     "Name": ["Aman", "Riya", "Vikas"],
#     "Age": [20, 21, 22]
# })
# # Age column remove
# df = df.drop("Age", axis=1)

# print(df)

In [151]:
# Modify dataframe
df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Vikas"],
    "Age": [20, 21, 22]
})

# Directly modify DataFrame
df.drop("Age", axis=1, inplace=True)

print(df)

    Name
0   Aman
1   Riya
2  Vikas

## Detecting & Removing Duplicates
- `duplicated()` → returns a Boolean Series marking duplicate rows.
- `drop_duplicates()` → remove duplicate rows.
- You can specify `subset` (columns) and `keep` ('first', 'last', or False).

In [152]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "David"],
    "Age": [25, 30, 35, 25, 30, 40],
    "Score": [88, 92, 79, 88, 92, 85]
}

df = pd.DataFrame(data)
df.drop_duplicates()

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
5    David   40     85

## Mini Practice
1. Create a messy DataFrame with missing values, wrong data types, typos, extra columns, and duplicates.
2. Clean it step-by-step using what you learned:
   - Handle missing values
   - Change data types
   - Replace incorrect values
   - Drop unnecessary rows/columns
   - Remove duplicates

In [153]:
import pandas as pd
import numpy as np

# 1. Create a messy DataFrame
data = {
    "Name": ["Alice", "Bob", "Chrlie", "David", "Alice", None],
    "Age": ["25", "30", None, "40", "25", "30"],      # ages stored as strings, with missing value
    "City": ["Delhi", "Mumbai", "Pun", "Bangalore", "Delhi", "Mumbai"],  # typo: "Pun" -> "Pune"
    "Score": [85, None, 78, 88, 85, 91],              # missing value in Score
    "Extra": ["x", "y", "z", "x", "y", "z"]           # extra column we don't really need
}

df = pd.DataFrame(data)

print("Original messy DataFrame:")
print(df)

# 2. Handle missing values
# Fill or drop as needed

# 3. Change data types
# Convert Age to int, Score to float, etc.

# 4. Replace incorrect values
# Fix 'Pun' -> 'Pune', maybe unify Name spellings if needed

# 5. Drop unnecessary rows/columns
# Remove 'Extra' or any row you don't want

# 6. Remove duplicates
# Use duplicated() and drop_duplicates()

# 7. Final clean DataFrame
# Print the cleaned DataFrame and check info()

Original messy DataFrame:
     Name  Age       City  Score Extra
0   Alice   25      Delhi   85.0     x
1     Bob   30     Mumbai    NaN     y
2  Chrlie  NaN        Pun   78.0     z
3   David   40  Bangalore   88.0     x
4   Alice   25      Delhi   85.0     y
5     NaN   30     Mumbai   91.0     z

In [154]:
from numpy import mean
# 2. Handle missing values
# Fill or drop as needed

df["Name"] = df["Name"].fillna("Unknown")
df["Age"] = df["Age"].fillna("88")

df

      Name Age       City  Score Extra
0    Alice  25      Delhi   85.0     x
1      Bob  30     Mumbai    NaN     y
2   Chrlie  88        Pun   78.0     z
3    David  40  Bangalore   88.0     x
4    Alice  25      Delhi   85.0     y
5  Unknown  30     Mumbai   91.0     z

In [155]:
# 3. Change data types
# Convert Age to int, Score to float, etc.
df['Age']=df['Age'].astype(int)
df['Score']=df['Score'].astype(float)
df["Score"] = df["Score"].fillna(df["Score"].mean())



df

      Name  Age       City  Score Extra
0    Alice   25      Delhi   85.0     x
1      Bob   30     Mumbai   85.4     y
2   Chrlie   88        Pun   78.0     z
3    David   40  Bangalore   88.0     x
4    Alice   25      Delhi   85.0     y
5  Unknown   30     Mumbai   91.0     z

In [156]:
# 5. Drop unnecessary rows/columns
# Remove 'Extra' or any row you don't want
df.drop("Extra", axis=1, inplace=True)

In [158]:
# 4. Replace incorrect values
# Fix 'Pun' -> 'Pune', maybe unify Name spellings if needed
df["City"] = df["City"].replace("Pun", "Pune")
df["Name"] = df["Name"].replace("Chrlie", "Charlie")
df

      Name  Age       City  Score
0    Alice   25      Delhi   85.0
1      Bob   30     Mumbai   85.4
2  Charlie   88       Pune   78.0
3    David   40  Bangalore   88.0
4    Alice   25      Delhi   85.0
5  Unknown   30     Mumbai   91.0

In [159]:
# 6. Remove duplicates
# Use duplicated() and drop_duplicates()

df.drop_duplicates()

      Name  Age       City  Score
0    Alice   25      Delhi   85.0
1      Bob   30     Mumbai   85.4
2  Charlie   88       Pune   78.0
3    David   40  Bangalore   88.0
5  Unknown   30     Mumbai   91.0

In [ ]:
# 7. Final clean DataFrame
# Print the cleaned DataFrame and check info()

      Name  Age       City  Score
0    Alice   25      Delhi   85.0
1      Bob   30     Mumbai   85.4
2  Charlie   88       Pune   78.0
3    David   40  Bangalore   88.0
4    Alice   25      Delhi   85.0
5  Unknown   30     Mumbai   91.0

---
## Summary
- Learned to handle missing values (`isna`, `dropna`, `fillna`).
- Converted column data types with `astype`.
- Cleaned up incorrect entries with `replace`.
- Removed unwanted rows/columns with `drop`.
- Detected and removed duplicates.