# 🐼 Pandas - Class 7: Merging, Joining & Concatenation
Welcome to **Class 7** of our Pandas series. Today we’ll learn how to combine multiple DataFrames using different techniques.

## 1. Using `concat()` for Stacking Data
- `pd.concat()` combines DataFrames vertically (rows) or horizontally (columns).
- Use `axis=0` for vertical stacking (default), `axis=1` for horizontal.
- `ignore_index=True` can reset the index after concatenation.

In [1]:

# Dataset 1: Product details
import pandas as pd

# Dataset 1: Product details
df1 = pd.DataFrame({
    "Product_ID": [101, 102, 103, 104, 105],
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Printer"],
    "Price": [55000, 700, 1500, 12000, 8500],
    "Stock": [15, 100, 60, 25, 18]
})

print("Dataset 1")
df1


# Dataset 2: More products (same columns as df1 → good for vertical stacking)
df2 = pd.DataFrame({
    "Product_ID": [106, 107, 108, 109, 110],
    "Product": ["Speaker", "Webcam", "Headphones", "Tablet", "SSD"],
    "Price": [2500, 1800, 3200, 28000, 6500],
    "Stock": [40, 30, 45, 20, 55]
})


df2


# Dataset 3: Additional info (different columns → good for horizontal stacking)

df3 = pd.DataFrame({
    "Category": ["Electronics", "Accessories", "Accessories", "Electronics", "Electronics"],
    "Brand": ["Dell", "Logitech", "HP", "Samsung", "Canon"],
    "Rating": [4.5, 4.3, 4.2, 4.6, 4.4]
})
df3

Dataset 1

      Category     Brand  Rating
0  Electronics      Dell     4.5
1  Accessories  Logitech     4.3
2  Accessories        HP     4.2
3  Electronics   Samsung     4.6
4  Electronics     Canon     4.4

In [2]:
pd.concat([df1,df2],ignore_index=True)

   Product_ID     Product  Price  Stock
0         101      Laptop  55000     15
1         102       Mouse    700    100
2         103    Keyboard   1500     60
3         104     Monitor  12000     25
4         105     Printer   8500     18
5         106     Speaker   2500     40
6         107      Webcam   1800     30
7         108  Headphones   3200     45
8         109      Tablet  28000     20
9         110         SSD   6500     55

In [3]:
product=pd.concat([df1,df2], axis=1, ignore_index=False)
product

   Product_ID   Product  Price  Stock  Product_ID     Product  Price  Stock
0         101    Laptop  55000     15         106     Speaker   2500     40
1         102     Mouse    700    100         107      Webcam   1800     30
2         103  Keyboard   1500     60         108  Headphones   3200     45
3         104   Monitor  12000     25         109      Tablet  28000     20
4         105   Printer   8500     18         110         SSD   6500     55

## 2. Using `merge()` for SQL-Style Joins
- `merge()` is similar to SQL joins.
- Specify `on` or `left_on`/`right_on` to choose key columns.
- Join types: `inner` (default), `left`, `right`, `outer`.

In [4]:
df4 = pd.DataFrame({
    "Product_ID": [101, 103, 104, 106, 108, 110],
    "Units_Sold": [120, 85, 60, 45, 70, 30],
    "Price": [6600000, 127500, 720000, 112500, 224000, 195000]
})
df4

   Product_ID  Units_Sold    Price
0         101         120  6600000
1         103          85   127500
2         104          60   720000
3         106          45   112500
4         108          70   224000
5         110          30   195000

In [5]:
pd.merge(df4, df1, on="Product_ID")

   Product_ID  Units_Sold  Price_x   Product  Price_y  Stock
0         101         120  6600000    Laptop    55000     15
1         103          85   127500  Keyboard     1500     60
2         104          60   720000   Monitor    12000     25

In [6]:
pd.merge(df4, df1, on="Product_ID",how="right")

   Product_ID  Units_Sold    Price_x   Product  Price_y  Stock
0         101       120.0  6600000.0    Laptop    55000     15
1         102         NaN        NaN     Mouse      700    100
2         103        85.0   127500.0  Keyboard     1500     60
3         104        60.0   720000.0   Monitor    12000     25
4         105         NaN        NaN   Printer     8500     18

In [7]:
pd.merge(df4, df1, on="Product_ID",how="left")

   Product_ID  Units_Sold  Price_x   Product  Price_y  Stock
0         101         120  6600000    Laptop  55000.0   15.0
1         103          85   127500  Keyboard   1500.0   60.0
2         104          60   720000   Monitor  12000.0   25.0
3         106          45   112500       NaN      NaN    NaN
4         108          70   224000       NaN      NaN    NaN
5         110          30   195000       NaN      NaN    NaN

In [8]:
pd.merge(df4, df1, on="Product_ID",how="inner") # it includes only the common items in both the tables

   Product_ID  Units_Sold  Price_x   Product  Price_y  Stock
0         101         120  6600000    Laptop    55000     15
1         103          85   127500  Keyboard     1500     60
2         104          60   720000   Monitor    12000     25

In [9]:
pd.merge(df4, df1, on="Product_ID",how="outer") #it inlcludes the whole both tables

   Product_ID  Units_Sold    Price_x   Product  Price_y  Stock
0         101       120.0  6600000.0    Laptop  55000.0   15.0
1         102         NaN        NaN     Mouse    700.0  100.0
2         103        85.0   127500.0  Keyboard   1500.0   60.0
3         104        60.0   720000.0   Monitor  12000.0   25.0
4         105         NaN        NaN   Printer   8500.0   18.0
5         106        45.0   112500.0       NaN      NaN    NaN
6         108        70.0   224000.0       NaN      NaN    NaN
7         110        30.0   195000.0       NaN      NaN    NaN

## 3. Using `join()` with Index Alignment
- `join()` joins DataFrames on their index or on a key column.
- By default, joins on index; can specify `on='col'`.
- Useful for adding columns to an existing DataFrame.

In [10]:
p_data=df1.set_index("Product_ID")
p_data

             Product  Price  Stock
Product_ID
101           Laptop  55000     15
102            Mouse    700    100
103         Keyboard   1500     60
104          Monitor  12000     25
105          Printer   8500     18

In [11]:
p_data.join(df3)

             Product  Price  Stock Category Brand  Rating
Product_ID
101           Laptop  55000     15      NaN   NaN     NaN
102            Mouse    700    100      NaN   NaN     NaN
103         Keyboard   1500     60      NaN   NaN     NaN
104          Monitor  12000     25      NaN   NaN     NaN
105          Printer   8500     18      NaN   NaN     NaN

## 4. Practical Examples
- Combine sales and revenue data to see performance.
- Merge students with marks to link records.
- Practice with realistic datasets to understand alignment and missing data handling.

## Mini Practice
1. Create three DataFrames: Products, Sales, and Revenue.
2. Concatenate them vertically and horizontally.
3. Merge Sales and Revenue using different join types.
4. Join Products with Sales based on index or a key.
5. Analyze missing values after joins.

In [12]:

# 1. Create three DataFrames: Products, Sales, and Revenue

products = pd.DataFrame({
    "Product_ID": [101, 102, 103, 104, 105],
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Printer"],
    "Category": ["Electronics", "Accessories", "Accessories", "Electronics", "Office"],
    "Price": [55000, 700, 1500, 12000, 8500]
})

sales = pd.DataFrame({
    "Product_ID": [101, 102, 103, 106, 107],
    "Units_Sold": [120, 350, 200, 80, 50],
    "Month": ["Jan", "Jan", "Jan", "Jan", "Jan"]
})

revenue = pd.DataFrame({
    "Product_ID": [101, 103, 104, 105, 108],
    "Revenue": [6600000, 300000, 720000, 425000, 520000],
    "Profit": [1200000, 70000, 150000, 90000, 110000]
})

print(product)
print("================================================================================")
print(sales)
print("============================")
print(revenue)

   Product_ID   Product  Price  Stock  Product_ID     Product  Price  Stock
0         101    Laptop  55000     15         106     Speaker   2500     40
1         102     Mouse    700    100         107      Webcam   1800     30
2         103  Keyboard   1500     60         108  Headphones   3200     45
3         104   Monitor  12000     25         109      Tablet  28000     20
4         105   Printer   8500     18         110         SSD   6500     55
================================================================================
   Product_ID  Units_Sold Month
0         101         120   Jan
1         102         350   Jan
2         103         200   Jan
3         106          80   Jan
4         107          50   Jan
============================
   Product_ID  Revenue   Profit
0         101  6600000  1200000
1         103   300000    70000
2         104   720000   150000
3         105   425000    90000
4         108   520000   110000

In [13]:
# 2. Concatenate them vertically and horizontally
# Write your code here
pd.concat([products, sales, revenue], axis=0, ignore_index=True)

,Product_ID,Product,Category,Price,Units_Sold,Month,Revenue,Profit
0,101,Laptop,Electronics,55000.0,NaN,NaN,NaN,NaN
1,102,Mouse,Accessories,700.0,NaN,NaN,NaN,NaN
2,103,Keyboard,Accessories,1500.0,NaN,NaN,NaN,NaN
3,104,Monitor,Electronics,12000.0,NaN,NaN,NaN,NaN
4,105,Printer,Office,8500.0,NaN,NaN,NaN,NaN
5,101,NaN,NaN,NaN,120.0,Jan,NaN,NaN
6,102,NaN,NaN,NaN,350.0,Jan,NaN,NaN
7,103,NaN,NaN,NaN,200.0,Jan,NaN,NaN
8,106,NaN,NaN,NaN,80.0,Jan,NaN,NaN
9,107,NaN,NaN,NaN,50.0,Jan,NaN,NaN
10,101,NaN,NaN,NaN,NaN,NaN,6600000.0,1200000.0
11,103,NaN,NaN,NaN,NaN,NaN,300000.0,70000.0
12,104,NaN,NaN,NaN,NaN,NaN,720000.0,150000.0
13,105,NaN,NaN,NaN,NaN,NaN,425000.0,90000.0
14,108,NaN,NaN,NaN,NaN,NaN,520000.0,110000.0

In [14]:
# 3. Merge Sales and Revenue using different join types (inner, left, right, outer)
# Write your code here
pd.merge(sales,revenue, how= "right")

   Product_ID  Units_Sold Month  Revenue   Profit
0         101       120.0   Jan  6600000  1200000
1         103       200.0   Jan   300000    70000
2         104         NaN   NaN   720000   150000
3         105         NaN   NaN   425000    90000
4         108         NaN   NaN   520000   110000

In [15]:
pd.merge(sales,revenue, how= "left")

   Product_ID  Units_Sold Month    Revenue     Profit
0         101         120   Jan  6600000.0  1200000.0
1         102         350   Jan        NaN        NaN
2         103         200   Jan   300000.0    70000.0
3         106          80   Jan        NaN        NaN
4         107          50   Jan        NaN        NaN

In [16]:
pd.merge(sales,revenue, how= "outer")

   Product_ID  Units_Sold Month    Revenue     Profit
0         101       120.0   Jan  6600000.0  1200000.0
1         102       350.0   Jan        NaN        NaN
2         103       200.0   Jan   300000.0    70000.0
3         104         NaN   NaN   720000.0   150000.0
4         105         NaN   NaN   425000.0    90000.0
5         106        80.0   Jan        NaN        NaN
6         107        50.0   Jan        NaN        NaN
7         108         NaN   NaN   520000.0   110000.0

In [17]:
pd.merge(sales,revenue, how= "inner")

   Product_ID  Units_Sold Month  Revenue   Profit
0         101         120   Jan  6600000  1200000
1         103         200   Jan   300000    70000

In [18]:
# 4. Join Products with Sales based on index or a key
# Write your code here

products.set_index("Product_ID").join(sales.set_index("Product_ID"),how="left")

             Product     Category  Price  Units_Sold Month
Product_ID
101           Laptop  Electronics  55000       120.0   Jan
102            Mouse  Accessories    700       350.0   Jan
103         Keyboard  Accessories   1500       200.0   Jan
104          Monitor  Electronics  12000         NaN   NaN
105          Printer       Office   8500         NaN   NaN

In [19]:
# 5. Analyze missing values after joins
# Use isna(), info(), or describe() to explore gaps
# Write your code here

---
## Summary
- Used `concat()` for stacking data vertically and horizontally.
- Performed SQL-style joins with `merge()`.
- Applied `join()` with index alignment.
- Explored practical use-cases like sales vs revenue, students vs marks.