# 🐼 Pandas - Class 7: Merging, Joining & Concatenation
Welcome to **Class 7** of our Pandas series. Today we’ll learn how to combine multiple DataFrames using different techniques.

## 1. Using `concat()` for Stacking Data
- `pd.concat()` combines DataFrames vertically (rows) or horizontally (columns).
- Use `axis=0` for vertical stacking (default), `axis=1` for horizontal.
- `ignore_index=True` can reset the index after concatenation.

In [33]:

# Dataset 1: Product details
import pandas as pd

# Dataset 1: Product details
df1 = pd.DataFrame({
    "Product_ID": [101, 102, 103, 104, 105],
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Printer"],
    "Price": [55000, 700, 1500, 12000, 8500],
    "Stock": [15, 100, 60, 25, 18]
})

print("Dataset 1")
df1


# Dataset 2: More products (same columns as df1 → good for vertical stacking)
df2 = pd.DataFrame({
    "Product_ID": [106, 107, 108, 109, 110],
    "Product": ["Speaker", "Webcam", "Headphones", "Tablet", "SSD"],
    "Price": [2500, 1800, 3200, 28000, 6500],
    "Stock": [40, 30, 45, 20, 55]
})


df2


# Dataset 3: Additional info (different columns → good for horizontal stacking)

df3 = pd.DataFrame({
    "Category": ["Electronics", "Accessories", "Accessories", "Electronics", "Electronics"],
    "Brand": ["Dell", "Logitech", "HP", "Samsung", "Canon"],
    "Rating": [4.5, 4.3, 4.2, 4.6, 4.4]
})
df3

Dataset 1

      Category     Brand  Rating
0  Electronics      Dell     4.5
1  Accessories  Logitech     4.3
2  Accessories        HP     4.2
3  Electronics   Samsung     4.6
4  Electronics     Canon     4.4

In [34]:
pd.concat([df1,df2],ignore_index=True)

   Product_ID     Product  Price  Stock
0         101      Laptop  55000     15
1         102       Mouse    700    100
2         103    Keyboard   1500     60
3         104     Monitor  12000     25
4         105     Printer   8500     18
5         106     Speaker   2500     40
6         107      Webcam   1800     30
7         108  Headphones   3200     45
8         109      Tablet  28000     20
9         110         SSD   6500     55

In [39]:
product=pd.concat([df1,df2], axis=1, ignore_index=False)
product

   Product_ID   Product  Price  Stock  Product_ID     Product  Price  Stock
0         101    Laptop  55000     15         106     Speaker   2500     40
1         102     Mouse    700    100         107      Webcam   1800     30
2         103  Keyboard   1500     60         108  Headphones   3200     45
3         104   Monitor  12000     25         109      Tablet  28000     20
4         105   Printer   8500     18         110         SSD   6500     55

## 2. Using `merge()` for SQL-Style Joins
- `merge()` is similar to SQL joins.
- Specify `on` or `left_on`/`right_on` to choose key columns.
- Join types: `inner` (default), `left`, `right`, `outer`.

In [40]:
df4 = pd.DataFrame({
    "Product_ID": [101, 103, 104, 106, 108, 110],
    "Units_Sold": [120, 85, 60, 45, 70, 30],
    "Price": [6600000, 127500, 720000, 112500, 224000, 195000]
})
df4

   Product_ID  Units_Sold    Price
0         101         120  6600000
1         103          85   127500
2         104          60   720000
3         106          45   112500
4         108          70   224000
5         110          30   195000

In [41]:
pd.merge(df4, df1, on="Product_ID")

   Product_ID  Units_Sold  Price_x   Product  Price_y  Stock
0         101         120  6600000    Laptop    55000     15
1         103          85   127500  Keyboard     1500     60
2         104          60   720000   Monitor    12000     25

In [42]:
pd.merge(df4, df1, on="Product_ID",how="right")

   Product_ID  Units_Sold    Price_x   Product  Price_y  Stock
0         101       120.0  6600000.0    Laptop    55000     15
1         102         NaN        NaN     Mouse      700    100
2         103        85.0   127500.0  Keyboard     1500     60
3         104        60.0   720000.0   Monitor    12000     25
4         105         NaN        NaN   Printer     8500     18

In [43]:
pd.merge(df4, df1, on="Product_ID",how="left")

   Product_ID  Units_Sold  Price_x   Product  Price_y  Stock
0         101         120  6600000    Laptop  55000.0   15.0
1         103          85   127500  Keyboard   1500.0   60.0
2         104          60   720000   Monitor  12000.0   25.0
3         106          45   112500       NaN      NaN    NaN
4         108          70   224000       NaN      NaN    NaN
5         110          30   195000       NaN      NaN    NaN

## 3. Using `join()` with Index Alignment
- `join()` joins DataFrames on their index or on a key column.
- By default, joins on index; can specify `on='col'`.
- Useful for adding columns to an existing DataFrame.

## 4. Practical Examples
- Combine sales and revenue data to see performance.
- Merge students with marks to link records.
- Practice with realistic datasets to understand alignment and missing data handling.

## Mini Practice
1. Create three DataFrames: Products, Sales, and Revenue.
2. Concatenate them vertically and horizontally.
3. Merge Sales and Revenue using different join types.
4. Join Products with Sales based on index or a key.
5. Analyze missing values after joins.

In [ ]:

# 1. Create three DataFrames: Products, Sales, and Revenue

# 2. Concatenate them vertically and horizontally
# Write your code here

# 3. Merge Sales and Revenue using different join types (inner, left, right, outer)
# Write your code here

# 4. Join Products with Sales based on index or a key
# Write your code here

# 5. Analyze missing values after joins
# Use isna(), info(), or describe() to explore gaps
# Write your code here

---
## Summary
- Used `concat()` for stacking data vertically and horizontally.
- Performed SQL-style joins with `merge()`.
- Applied `join()` with index alignment.
- Explored practical use-cases like sales vs revenue, students vs marks.