# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [20]:
import pandas as pd

# Create dummy data
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma", "Frank", "Grace", "Henry"],
    "Age": [23, 25, 22, 24, 26, 21, 27, 23],
    "Score": [88, 75, 92, 85, 79, 90, 95, 82]
}
b = pd.DataFrame(data)
print(b)
print("=====================")
b[b['Score']>=90]

      Name  Age  Score
0    Alice   23     88
1      Bob   25     75
2  Charlie   22     92
3    David   24     85
4     Emma   26     79
5    Frank   21     90
6    Grace   27     95
7    Henry   23     82
=====================

      Name  Age  Score
2  Charlie   22     92
5    Frank   21     90
6    Grace   27     95

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

In [21]:
b[(b['Score']>=90) & (b['Age']>23) ]

    Name  Age  Score
6  Grace   27     95

In [22]:
b[(b['Score']>=90) | (b['Age']>23) ]

      Name  Age  Score
1      Bob   25     75
2  Charlie   22     92
3    David   24     85
4     Emma   26     79
5    Frank   21     90
6    Grace   27     95

In [ ]:
b[~b['Score']>=90]

      Name  Age  Score
0    Alice   23     88
1      Bob   25     75
2  Charlie   22     92
3    David   24     85
4     Emma   26     79
5    Frank   21     90
6    Grace   27     95
7    Henry   23     82

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [23]:


# 1. Build a DataFrame with columns: Name, Age, City, Score


# 2. Use boolean indexing to select rows where Age > 25
# Write your code here

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.