# 🐼 Pandas - Class 11: Advanced Tricks & Performance
Welcome to **Class 11** of our Pandas series. Today we’ll explore advanced techniques to write efficient, clean, and optimized Pandas code.

## 1. Applying Custom Functions with `apply()` / `map()`
- `apply()` lets you apply a custom function across rows or columns.
- `map()` is for applying functions element-wise to a Series.
- Both are handy for transformations, calculations, and cleaning data.

In [2]:
import pandas as pd

# DataFrame: Marks of 5 children
df = pd.DataFrame({
    "Name": ["Aarav", "Diya", "Rohan", "Meera", "Vivaan"],
    "Science": [85, 92, 78, 88, 95],
    "Maths": [90, 87, 82, 91, 89]
})

df

     Name  Science  Maths
0   Aarav       85     90
1    Diya       92     87
2   Rohan       78     82
3   Meera       88     91
4  Vivaan       95     89

In [4]:
df['Total Marks'] = df[['Maths','Science']].apply(lambda rows:rows.sum(), axis=1)
df

     Name  Science  Maths  Total Marks
0   Aarav       85     90          175
1    Diya       92     87          179
2   Rohan       78     82          160
3   Meera       88     91          179
4  Vivaan       95     89          184