# 🐼 Pandas - Class 5: Sorting & Basic Statistics
Welcome to **Class 5** of our Pandas series. Today we’ll learn how to sort data and calculate basic statistics.

## 1. Sorting Data
- Use `sort_values(by='col')` to sort by column values.
- Use `ascending=False` for descending order.
- Sort by multiple columns by passing a list.
- `sort_index()` sorts by row or column index.

In [12]:
import pandas as pd

data = {
    "Product": [
        "Laptop", "Smartphone", "Tablet", "Monitor", "Keyboard",
        "Mouse", "Printer", "Headphones", "Speaker", "Webcam",
        "Power Bank", "SSD", "Router", "USB Cable", "Charger",
        "Smart Watch", "Gaming Chair", "Microphone", "Projector", "Camera"
    ],

    "Price": [
        85000, 65000, 35000, 18000, 2500,
        1200, 15000, 4500, 6000, 3500,
        2200, 7500, 3200, 400, 1500,
        12000, 18000, 5500, 42000, 68000
    ],

    "Stock": [
        25, 40, 18, 30, 85,
        120, 12, 60, 35, 28,
        75, 50, 38, 200, 110,
        22, 10, 18, 8, 11
    ],

    "Rating": [
        4.7, 4.6, 4.5, 4.4, 4.3,
        4.2, 4.1, 4.6, 4.4, 4.3,
        4.5, 4.8, 4.2, 4.1, 4.3,
        4.7, 4.8, 4.5, 4.6, 4.8
    ]
}

df = pd.DataFrame(data)

df

         Product  Price  Stock  Rating
0         Laptop  85000     25     4.7
1     Smartphone  65000     40     4.6
2         Tablet  35000     18     4.5
3        Monitor  18000     30     4.4
4       Keyboard   2500     85     4.3
5          Mouse   1200    120     4.2
6        Printer  15000     12     4.1
7     Headphones   4500     60     4.6
8        Speaker   6000     35     4.4
9         Webcam   3500     28     4.3
10    Power Bank   2200     75     4.5
11           SSD   7500     50     4.8
12        Router   3200     38     4.2
13     USB Cable    400    200     4.1
14       Charger   1500    110     4.3
15   Smart Watch  12000     22     4.7
16  Gaming Chair  18000     10     4.8
17    Microphone   5500     18     4.5
18     Projector  42000      8     4.6
19        Camera  68000     11     4.8

In [13]:
df.sort_values(by= 'Price', ascending= False) # acending = false is used to get op in decending order

         Product  Price  Stock  Rating
0         Laptop  85000     25     4.7
19        Camera  68000     11     4.8
1     Smartphone  65000     40     4.6
18     Projector  42000      8     4.6
2         Tablet  35000     18     4.5
3        Monitor  18000     30     4.4
16  Gaming Chair  18000     10     4.8
6        Printer  15000     12     4.1
15   Smart Watch  12000     22     4.7
11           SSD   7500     50     4.8
8        Speaker   6000     35     4.4
17    Microphone   5500     18     4.5
7     Headphones   4500     60     4.6
9         Webcam   3500     28     4.3
12        Router   3200     38     4.2
4       Keyboard   2500     85     4.3
10    Power Bank   2200     75     4.5
14       Charger   1500    110     4.3
5          Mouse   1200    120     4.2
13     USB Cable    400    200     4.1

## 2. Descriptive Statistics
- `mean()`, `median()`, `mode()` for central tendency.
- `std()` for standard deviation.
- `describe()` for a summary of stats (count, mean, std, min, quartiles, max).

In [14]:
df.mean(numeric_only= True)

Price     19800.00
Stock        49.75
Rating        4.47
dtype: float64

In [15]:
df.median(numeric_only= True)

Price     6750.0
Stock       32.5
Rating       4.5
dtype: float64

In [16]:
df.mode(numeric_only= True)

     Price  Stock  Rating
0  18000.0   18.0     4.3
1      NaN    NaN     4.5
2      NaN    NaN     4.6
3      NaN    NaN     4.8

In [17]:
df.std(numeric_only= True)

Price     25566.610627
Stock        48.170612
Rating        0.229645
dtype: float64

## 3. Counting Values
- `value_counts()` shows the frequency of unique values in a Series.
- Use `normalize=True` to see percentages instead of counts.

In [18]:
df.value_counts('Product')

Product
Laptop          1
Smartphone      1
Tablet          1
Monitor         1
Keyboard        1
Mouse           1
Printer         1
Headphones      1
Speaker         1
Webcam          1
Power Bank      1
SSD             1
Router          1
USB Cable       1
Charger         1
Smart Watch     1
Gaming Chair    1
Microphone      1
Projector       1
Camera          1
Name: count, dtype: int64

In [19]:
df.value_counts('Product',normalize= True)

Product
Laptop          0.05
Smartphone      0.05
Tablet          0.05
Monitor         0.05
Keyboard        0.05
Mouse           0.05
Printer         0.05
Headphones      0.05
Speaker         0.05
Webcam          0.05
Power Bank      0.05
SSD             0.05
Router          0.05
USB Cable       0.05
Charger         0.05
Smart Watch     0.05
Gaming Chair    0.05
Microphone      0.05
Projector       0.05
Camera          0.05
Name: proportion, dtype: float64

## 4. Correlation & Covariance
- `corr()` computes correlation between numeric columns.
- `cov()` computes covariance.
- Correlation values range from -1 (negative) to +1 (positive).

In [20]:
df.corr(numeric_only=True)

           Price     Stock    Rating
Price   1.000000 -0.434105  0.529790
Stock  -0.434105  1.000000 -0.532637
Rating  0.529790 -0.532637  1.000000

In [21]:
df.cov(numeric_only=True)

               Price          Stock       Rating
Price   6.536516e+08 -534626.315789  3110.526316
Stock  -5.346263e+05    2320.407895    -5.892105
Rating  3.110526e+03      -5.892105     0.052737

## Mini Practice
1. Build a DataFrame with columns: Name, Age, Score, Height.
2. Sort the data by Score (descending).
3. Get mean, median, mode, and std of numeric columns.
4. Use value_counts on Name or any categorical column.
5. Compute corr() and cov() for all numeric columns.

In [27]:
# Write your mini practice solution here

# 1. Build a DataFrame with columns: Name, Age, Score, Height
data = {
    "Name": [
        "Alice", "Bob", "Charlie", "David", "Emma",
        "Frank", "Grace", "Henry", "Ivy", "Jack"
    ],
    "Age": [23, 25, 22, 24, 26, 21, 27, 23, 24, 22],
    "Score": [88, 75, 92, 85, 79, 90, 95, 82, 87, 91],
    "Height": [165, 172, 168, 180, 160, 175, 169, 182, 163, 177]
}

df = pd.DataFrame(data)
df

      Name  Age  Score  Height
0    Alice   23     88     165
1      Bob   25     75     172
2  Charlie   22     92     168
3    David   24     85     180
4     Emma   26     79     160
5    Frank   21     90     175
6    Grace   27     95     169
7    Henry   23     82     182
8      Ivy   24     87     163
9     Jack   22     91     177

In [28]:
# 2. Sort the data by Score (descending)
# Write your code here

df.sort_values(by= 'Score', ascending= False)

      Name  Age  Score  Height
6    Grace   27     95     169
2  Charlie   22     92     168
9     Jack   22     91     177
5    Frank   21     90     175
0    Alice   23     88     165
8      Ivy   24     87     163
3    David   24     85     180
7    Henry   23     82     182
4     Emma   26     79     160
1      Bob   25     75     172

In [24]:
# 3. Get mean, median, mode, and std of numeric columns
# Write your code here

In [25]:
# 4. Use value_counts on Name or any categorical column
# Write your code here

In [26]:
# 5. Compute corr() and cov() for all numeric columns
# Write your code here

---
## Summary
- Learned to sort by columns with `sort_values` and by index with `sort_index`.
- Explored descriptive statistics: mean, median, mode, std, describe.
- Counted values with `value_counts`.
- Calculated correlation and covariance.